### ISSUE TITLE
Cannot get this node working, pls help.

### ISSUE THREAD

**Issue by Design0815** [RodrigoSKohl/StableDesign-for-ComfyUI#2]
Hi, can anybody help with this problem. I cannot get this node too work. I tried several versions under Comfyui Portable. 

Greets

## Execute management script for 'C:\Users\xyz\Desktop\ComfyUI_windows_portable\ComfyUI\custom_nodes\interior-design-for-comfyui'
 Collecting xformers==0.0.23.post1
   Downloading xformers-0.0.23.post1.tar.gz (3.9 MB)
      ---------------------------------------- 3.9/3.9 MB 17.7 MB/s eta 0:00:00
   Installing build dependencies: started
   Installing build dependencies: finished with status 'done'
   Getting requirements to build wheel: started
   Getting requirements to build wheel: finished with status 'error'
[!]   error: subprocess-exited-with-error
[!]
[!]   Getting requirements to build wheel did not run successfully.
[!]   exit code: 1
[!]
[!]   [78 lines of output]
[!]   C:\Users\xyz\Desktop\ComfyUI_windows_portable\python_embeded\Lib\site-packages\setuptools\dist.py:760: SetuptoolsDeprecationWarning: License classifiers are deprecated.
[!]   !!
[!]
[!]           ********************************************************************************
[!]           Please consider removing the following classifiers in favor of a SPDX license expression:
[!]
[!]           License :: OSI Approved :: BSD License
[!]
[!]           See https://packaging.python.org/en/latest/guides/writing-pyproject-toml/#license for details.
[!]           ********************************************************************************
[!]
[!]   !!
[!]     self._finalize_license_expression()
[!]   running egg_info
[!]   writing xformers.egg-info\PKG-INFO
[!]   writing dependency_links to xformers.egg-info\dependency_links.txt
[!]   writing requirements to xformers.egg-info\requires.txt
[!]   writing top-level names to xformers.egg-info\top_level.txt
[!]   Traceback (most recent call last):
[!]     File "C:\Users\xyz\Desktop\ComfyUI_windows_portable\python_embeded\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 389, in <module>
[!]       main()
[!]     File "C:\Users\xyz\Desktop\ComfyUI_windows_portable\python_embeded\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 373, in main
[!]       json_out["return_val"] = hook(**hook_input["kwargs"])
[!]                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[!]     File "C:\Users\xyz\Desktop\ComfyUI_windows_portable\python_embeded\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 143, in get_requires_for_build_wheel
[!]       return hook(config_settings)
[!]              ^^^^^^^^^^^^^^^^^^^^^
[!]     File "C:\Users\xyz\Desktop\ComfyUI_windows_portable\python_embeded\Lib\site-packages\setuptools\build_meta.py", line 334, in get_requires_for_build_wheel
[!]       return self._get_build_requires(config_settings, requirements=[])
[!]              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[!]     File "C:\Users\xyz\Desktop\ComfyUI_windows_portable\python_embeded\Lib\site-packages\setuptools\build_meta.py", line 304, in _get_build_requires
[!]       self.run_setup()
[!]     File "C:\Users\xyz\Desktop\ComfyUI_windows_portable\python_embeded\Lib\site-packages\setuptools\build_meta.py", line 522, in run_setup
[!]       super().run_setup(setup_script=setup_script)
[!]     File "C:\Users\xyz\Desktop\ComfyUI_windows_portable\python_embeded\Lib\site-packages\setuptools\build_meta.py", line 320, in run_setup
[!]       exec(code, locals())
[!]     File "<string>", line 399, in <module>
[!]     File "C:\Users\xyz\Desktop\ComfyUI_windows_portable\python_embeded\Lib\site-packages\setuptools\__init__.py", line 117, in setup
[!]       return distutils.core.setup(**attrs)
[!]              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[!]     File "C:\Users\xyz\Desktop\ComfyUI_windows_portable\python_embeded\Lib\site-packages\setuptools\_distutils\core.py", line 186, in setup
[!]       return run_commands(dist)
[!]              ^^^^^^^^^^^^^^^^^^
[!]     File "C:\Users\xyz\Desktop\ComfyUI_windows_portable\python_embeded\Lib\site-packages\setuptools\_distutils\core.py", line 202, in run_commands
[!]       dist.run_commands()
[!]     File "C:\Users\xyz\Desktop\ComfyUI_windows_portable\python_embeded\Lib\site-packages\setuptools\_distutils\dist.py", line 1002, in run_commands
[!]       self.run_command(cmd)
[!]     File "C:\Users\xyz\Desktop\ComfyUI_windows_portable\python_embeded\Lib\site-packages\setuptools\dist.py", line 1105, in run_command
[!]       super().run_command(command)
[!]     File "C:\Users\xyz\Desktop\ComfyUI_windows_portable\python_embeded\Lib\site-packages\setuptools\_distutils\dist.py", line 1021, in run_command
[!]       cmd_obj.run()
[!]     File "C:\Users\xyz\Desktop\ComfyUI_windows_portable\python_embeded\Lib\site-packages\setuptools\command\egg_info.py", line 312, in run
[!]       self.find_sources()
[!]     File "C:\Users\xyz\Desktop\ComfyUI_windows_portable\python_embeded\Lib\site-packages\setuptools\command\egg_info.py", line 320, in find_sources
[!]       mm.run()
[!]     File "C:\Users\xyz\Desktop\ComfyUI_windows_portable\python_embeded\Lib\site-packages\setuptools\command\egg_info.py", line 543, in run
[!]       self.add_defaults()
[!]     File "C:\Users\xyz\Desktop\ComfyUI_windows_portable\python_embeded\Lib\site-packages\setuptools\command\egg_info.py", line 581, in add_defaults
[!]       sdist.add_defaults(self)
[!]     File "C:\Users\xyz\Desktop\ComfyUI_windows_portable\python_embeded\Lib\site-packages\setuptools\command\sdist.py", line 109, in add_defaults
[!]       super().add_defaults()
[!]     File "C:\Users\xyz\Desktop\ComfyUI_windows_portable\python_embeded\Lib\site-packages\setuptools\_distutils\command\sdist.py", line 245, in add_defaults
[!]       self._add_defaults_ext()
[!]     File "C:\Users\xyz\Desktop\ComfyUI_windows_portable\python_embeded\Lib\site-packages\setuptools\_distutils\command\sdist.py", line 329, in _add_defaults_ext
[!]       build_ext = self.get_finalized_command('build_ext')
[!]                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[!]     File "C:\Users\xyz\Desktop\ComfyUI_windows_portable\python_embeded\Lib\site-packages\setuptools\_distutils\cmd.py", line 333, in get_finalized_command
[!]       cmd_obj = self.distribution.get_command_obj(command, create)
[!]                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[!]     File "C:\Users\xyz\Desktop\ComfyUI_windows_portable\python_embeded\Lib\site-packages\setuptools\_distutils\dist.py", line 885, in get_command_obj
[!]       cmd_obj = self.command_obj[command] = klass(self)
[!]                                             ^^^^^^^^^^^
[!]     File "C:\Users\xyz\Desktop\ComfyUI_windows_portable\python_embeded\Lib\site-packages\torch\utils\cpp_extension.py", line 515, in __init__
[!]       super().__init__(*args, **kwargs)
[!]     File "<string>", line 352, in __init__
[!]     File "C:\Users\xyz\Desktop\ComfyUI_windows_portable\python_embeded\Lib\site-packages\torch\utils\cpp_extension.py", line 520, in __init__
[!]       super().__init__(*args, **kwargs)
[!]   TypeError: Command.__init__() got an unexpected keyword argument 'no_python_abi_suffix'
[!]   [end of output]
[!]
[!]   note: This error originates from a subprocess, and is likely not a problem with pip.
[!] error: subprocess-exited-with-error
[!]
[!] Getting requirements to build wheel did not run successfully.
[!] exit code: 1
[!]
[!] See above for output.
[!]
[!] note: This error originates from a subprocess, and is likely not a problem with pip.
management script failed: C:\Users\xyz\Desktop\ComfyUI_windows_portable\ComfyUI\custom_nodes\interior-design-for-comfyui
[SKIP] Downgrading pip package isn't allowed: transformers (cur=4.50.0)

## Execute management script for 'C:\Users\xyz\Desktop\ComfyUI_windows_portable\ComfyUI\custom_nodes\interior-design-for-comfyui'
 Collecting accelerate==0.26.1
   Downloading accelerate-0.26.1-py3-none-any.whl.metadata (18 kB)
                        Downloading accelerate-0.26.1-py3-none-any.whl (270 kB)
 Installing collected packages: accelerate
 Successfully installed accelerate-0.26.1

## Execute management script for 'C:\Users\xyz\Desktop\ComfyUI_windows_portable\ComfyUI\custom_nodes\interior-design-for-comfyui'
 Collecting opencv-python==4.9.0.80
   Downloading opencv_python-4.9.0.80-cp37-abi3-win_amd64.whl.metadata (20 kB)
  Downloading opencv_python-4.9.0.80-cp37-abi3-win_amd64.whl (38.6 MB)
    ---------------------------------------- 38.6/38.6 MB 38.4 MB/s eta 0:00:00
 Installing collected packages: opencv-python
 Successfully installed opencv-python-4.9.0.80

## Execute management script for 'C:\Users\xyz\Desktop\ComfyUI_windows_portable\ComfyUI\custom_nodes\interior-design-for-comfyui'
[!] ERROR: Could not find a version that satisfies the requirement triton==2.1.0 (from versions: none)
[!] ERROR: No matching distribution found for triton==2.1.0
management script failed: C:\Users\xyz\Desktop\ComfyUI_windows_portable\ComfyUI\custom_nodes\interior-design-for-comfyui

## Execute management script for 'C:\Users\xyz\Desktop\ComfyUI_windows_portable\ComfyUI\custom_nodes\interior-design-for-comfyui'
 Collecting altair==4.1.0
   Downloading altair-4.1.0-py3-none-any.whl.metadata (13 kB)
 Collecting entrypoints (from altair==4.1.0)
   Downloading entrypoints-0.4-py3-none-any.whl.metadata (2.6 kB)
  Collecting jsonschema (from altair==4.1.0)
   Downloading jsonschema-4.23.0-py3-none-any.whl.metadata (7.9 kB)
  Collecting pandas>=0.18 (from altair==4.1.0)
   Downloading pandas-2.2.3-cp312-cp312-win_amd64.whl.metadata (19 kB)
 Collecting toolz (from altair==4.1.0)
   Downloading toolz-1.0.0-py3-none-any.whl.metadata (5.1 kB)
 Collecting python-dateutil>=2.8.2 (from pandas>=0.18->altair==4.1.0)
   Downloading python_dateutil-2.9.0.post0-py2.py3-none-any.whl.metadata (8.4 kB)
 Collecting pytz>=2020.1 (from pandas>=0.18->altair==4.1.0)
   Downloading pytz-2025.2-py2.py3-none-any.whl.metadata (22 kB)
 Collecting tzdata>=2022.7 (from pandas>=0.18->altair==4.1.0)
   Downloading tzdata-2025.2-py2.py3-none-any.whl.metadata (1.4 kB)
   Collecting jsonschema-specifications>=2023.03.6 (from jsonschema->altair==4.1.0)
   Downloading jsonschema_specifications-2024.10.1-py3-none-any.whl.metadata (3.0 kB)
 Collecting referencing>=0.28.4 (from jsonschema->altair==4.1.0)
   Downloading referencing-0.36.2-py3-none-any.whl.metadata (2.8 kB)
 Collecting rpds-py>=0.7.1 (from jsonschema->altair==4.1.0)
   Downloading rpds_py-0.24.0-cp312-cp312-win_amd64.whl.metadata (4.2 kB)
 Collecting six>=1.5 (from python-dateutil>=2.8.2->pandas>=0.18->altair==4.1.0)
   Downloading six-1.17.0-py2.py3-none-any.whl.metadata (1.7 kB)
  Downloading altair-4.1.0-py3-none-any.whl (727 kB)
    --------------------------------------- 727.8/727.8 kB 31.0 MB/s eta 0:00:00
 Downloading pandas-2.2.3-cp312-cp312-win_amd64.whl (11.5 MB)
    ---------------------------------------- 11.5/11.5 MB 37.9 MB/s eta 0:00:00
 Downloading entrypoints-0.4-py3-none-any.whl (5.3 kB)
 Downloading jsonschema-4.23.0-py3-none-any.whl (88 kB)
 Downloading toolz-1.0.0-py3-none-any.whl (56 kB)
 Downloading jsonschema_specifications-2024.10.1-py3-none-any.whl (18 kB)
 Downloading python_dateutil-2.9.0.post0-py2.py3-none-any.whl (229 kB)
 Downloading pytz-2025.2-py2.py3-none-any.whl (509 kB)
 Downloading referencing-0.36.2-py3-none-any.whl (26 kB)
 Downloading rpds_py-0.24.0-cp312-cp312-win_amd64.whl (239 kB)
 Downloading tzdata-2025.2-py2.py3-none-any.whl (347 kB)
 Downloading six-1.17.0-py2.py3-none-any.whl (11 kB)
 Installing collected packages: pytz, tzdata, toolz, six, rpds-py, entrypoints, referencing, python-dateutil, pandas, jsonschema-specifications, jsonschema, altair
 Successfully installed altair-4.1.0 entrypoints-0.4 jsonschema-4.23.0 jsonschema-specifications-2024.10.1 pandas-2.2.3 python-dateutil-2.9.0.post0 pytz-2025.2 referencing-0.36.2 rpds-py-0.24.0 six-1.17.0 toolz-1.0.0 tzdata-2025.2

## Execute management script for 'C:\Users\xyz\Desktop\ComfyUI_windows_portable\ComfyUI\custom_nodes\interior-design-for-comfyui'
 Collecting pandas==2.1.4
   Downloading pandas-2.1.4-cp312-cp312-win_amd64.whl.metadata (18 kB)
      Downloading pandas-2.1.4-cp312-cp312-win_amd64.whl (10.5 MB)
    ---------------------------------------- 10.5/10.5 MB 34.5 MB/s eta 0:00:00
 Installing collected packages: pandas
   Attempting uninstall: pandas
     Found existing installation: pandas 2.2.3
     Uninstalling pandas-2.2.3:
       Successfully uninstalled pandas-2.2.3
 Successfully installed pandas-2.1.4

**Comment by Design0815** [comment]
Tried several ways, and another installation. But i cant get it too work. Now its showing this: 

### ComfyUI Revision: 3288 [75c1c757] *DETACHED | Released on '2025-03-21'
Traceback (most recent call last):
  File "C:\Apps\ComfyUI_windows_portable\ComfyUI\nodes.py", line 2141, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "C:\Apps\ComfyUI_windows_portable\ComfyUI\custom_nodes\InteriorDesign-for-ComfyUI\__init__.py", line 1, in <module>
    from .node.node import InteriorDesignNode
  File "C:\Apps\ComfyUI_windows_portable\ComfyUI\custom_nodes\InteriorDesign-for-ComfyUI\node\node.py", line 4, in <module>
    from .pipeline import ControlNetDepthDesignModelMulti  # Seu pipeline original
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Apps\ComfyUI_windows_portable\ComfyUI\custom_nodes\InteriorDesign-for-ComfyUI\node\pipeline.py", line 7, in <module>
    from diffusers.pipelines.controlnet import StableDiffusionControlNetInpaintPipeline
  File "C:\Apps\ComfyUI_windows_portable\python_embeded\Lib\site-packages\diffusers\__init__.py", line 5, in <module>
    from .utils import (
  File "C:\Apps\ComfyUI_windows_portable\python_embeded\Lib\site-packages\diffusers\utils\__init__.py", line 37, in <module>
    from .dynamic_modules_utils import get_class_from_dynamic_module
  File "C:\Apps\ComfyUI_windows_portable\python_embeded\Lib\site-packages\diffusers\utils\dynamic_modules_utils.py", line 28, in <module>
    from huggingface_hub import cached_download, hf_hub_download, model_info
ImportError: cannot import name 'cached_download' from 'huggingface_hub' (C:\Apps\ComfyUI_windows_portable\python_embeded\Lib\site-packages\huggingface_hub\__init__.py). Did you mean: 'hf_hub_download'?

Cannot import C:\Apps\ComfyUI_windows_portable\ComfyUI\custom_nodes\InteriorDesign-for-ComfyUI module for custom nodes: cannot import name 'cached_download' from 'huggingface_hub' (C:\Apps\ComfyUI_windows_portable\python_embeded\Lib\site-packages\huggingface_hub\__init__.py)

**Comment by RodrigoSKohl** [comment]
At the moment this node only works on transformers version>=4.39.0,<=4.45.0. Check which version you have installed in your virtual environment, I recommend installing the requirements.txt that is in this repository to satisfy the required version of transformers and hugging face hub.

**Comment by RodrigoSKohl** [comment]
The last update of the node resolves the Hugging face and other dependecy problems. I reccomend to enter in the folder of the node and run `..\..\..\python_embeded\python.exe -s -m pip install -r requirements.txt` in the ComfyUI portable Windows version

**Comment by Design0815** [comment]
Hello Rodrigo, thanks a lot for this Info and work!
Works well now on my 4070ti.

Do you know how I could get It to work on the 5090 with ComfyUi? I tried several ways, but it wont work because by installation it also downgrades to torch 2.6  cu124  when i remember right. But RTX needs Cuda 12.8 when i unterstand right.

ComfyUI Node gets error like this, is there any workaround?

CUDA error: no kernel image is available for execution on the device
CUDA kerel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect For debugging consider passing CUDA_LAUNCH BLOCKING=1
Compile with "TORCH USE_CUDA_DSA' to enable device-side assertions.

Greetings!
